/* Generated By:JJTree: Do not edit this line. ASTUnaryPlus.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTUnaryPlus extends SimpleNode {
  public ASTUnaryPlus(int id) {
    super(id);
  }

  public ASTUnaryPlus(HexLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HexLangVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5ecc7a500f5bf0f432d5c3cc7c04eebb (do not edit this line) */
